server:
  port: 8082
  error:
    include-stacktrace: always

spring:
  application:
  name: authorization-server

datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 321griff

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

instance:
  instance-id: "${spring.application.name}:${server.port}"
  prefer-ip-address: true

JWT_SECRET_KEY: xJ29!mNf7qWz$eL0aPv9@bRt6UuKcY3d
EMAIL_TEMPLATE: /home/ceawse/IdeaProjects/in-snap-app/authorization-server/src/main/resources/email_template.html
