server:
  port: ${SERVER_PORT}
  error:
    include-stacktrace: always

spring:
  application:
    name: ${SPRING_APP_NAME}

datasource:
  driver: org.postgresql.Driver
  url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL}

instance:
  instance-id: "${spring.application.name}:${server.port}"
  prefer-ip-address: true

JWT_SECRET_KEY: ${JWT_SECRET_KEY}
EMAIL_TEMPLATE: ${EMAIL_TEMPLATE}
